# Generated by Django 6.0 on 2026-01-04 18:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('MedicID', models.AutoField(primary_key=True, serialize=False)),
                ('NumeMedic', models.CharField(max_length=100)),
                ('PrenumeMedic', models.CharField(max_length=100)),
                ('Specializare', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Medici',
                'db_table': 'medic',
            },
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('MedicamentID', models.AutoField(primary_key=True, serialize=False)),
                ('Denumire', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Medicamente',
                'db_table': 'medicament',
            },
        ),
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('PacientID', models.AutoField(primary_key=True, serialize=False)),
                ('CNP', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='CNP must be exactly 13 digits', regex='^\\d{13}$')])),
                ('NumePacient', models.CharField(max_length=100)),
                ('PrenumePacient', models.CharField(max_length=100)),
                ('Adresa', models.TextField(blank=True, null=True)),
                ('Asigurare', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Pacienti',
                'db_table': 'pacient',
            },
        ),
        migrations.CreateModel(
            name='Consultatie',
            fields=[
                ('ConsultatieID', models.AutoField(primary_key=True, serialize=False)),
                ('Data', models.DateField()),
                ('Diagnostic', models.TextField(blank=True, null=True)),
                ('DozaMedicament', models.CharField(blank=True, max_length=100, null=True)),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.medic')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.medicament')),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.pacient')),
            ],
            options={
                'verbose_name_plural': 'Consultatii',
                'db_table': 'consultatie',
            },
        ),
        migrations.CreateModel(
            name='MedicPacient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.medic')),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.pacient')),
            ],
            options={
                'verbose_name_plural': 'Medic-Pacient Relations',
                'db_table': 'medic_pacient',
                'unique_together': {('medic', 'pacient')},
            },
        ),
    ]
